# Generated by Django 4.0.6 on 2022-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(3, 'Not Bad'), (2, 'Bad'), (1, 'Worst'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
