# Generated by Django 4.0.6 on 2022-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(2, 'Bad'), (4, 'Good'), (3, 'Not Bad'), (1, 'Worst'), (5, 'Excellent')]),
        ),
    ]
