# Generated by Django 4.2.1 on 2023-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (4, 'Good'), (2, 'Bad'), (3, 'Not Bad'), (5, 'Excellent')]),
        ),
    ]
