# Generated by Django 4.2.1 on 2023-06-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_album_num_stars_alter_album_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(3, 'Not Bad'), (1, 'Worst'), (5, 'Excellent'), (4, 'Good'), (2, 'Bad')]),
        ),
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
